"""added color to cat

Revision ID: 940df6dd6a5f
Revises: b5c23de97742
Create Date: 2024-10-01 12:13:02.919818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940df6dd6a5f'
down_revision: Union[str, None] = 'b5c23de97742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cats', sa.Column('color', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cats', 'color')
    # ### end Alembic commands ###
