FROM python:3

WORKDIR /src
COPY . /workmate_app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /workmate_app/requirements.txt

